# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-bb38036f-b0c2-44d4-b34a-cd7474d738bb";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-bb38036f-b0c2-44d4-b34a-cd7474d738bb".device = "/dev/disk/by-uuid/bb38036f-b0c2-44d4-b34a-cd7474d738bb";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-bb38036f-b0c2-44d4-b34a-cd7474d738bb";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-bb38036f-b0c2-44d4-b34a-cd7474d738bb";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B1C9-A5D2";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-fa6ca2aa-a1ea-4a94-9f2d-6a9d78ba1878"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
