# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "uas" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-014faddd-95e8-4e0a-a0d6-3f3eb1d5d33c";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-014faddd-95e8-4e0a-a0d6-3f3eb1d5d33c".device = "/dev/disk/by-uuid/014faddd-95e8-4e0a-a0d6-3f3eb1d5d33c";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8C60-E9EF";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-b19e4fb2-d47e-4d14-87d8-617fab2d8c78"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
